version: "3.8"
services:
  slack:
    image: slackbot
    hostname: slackbot
    container_name: slackbot
    build:
      context: ./slackbot/
    env_file:
      - .env

  binance_stats_analyzer:
    image: binance_stats_analyzer
    hostname: binance_stats_analyzer
    container_name: binance_stats_analyzer
    build:
      context: ./binance_stats_analyzer/
    env_file:
      - .env

  text_analyzer:
    image: text_analyzer
    hostname: text_analyzer
    container_name: text_analyzer
    build:
      context: ./text_analyzer/
    env_file:
      - .env

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mqtt-broker
    env_file:
      - .env
    volumes:
      - ./mqtt-broker/:/mosquitto/
    ports:
      - 1883:1883
