version: "3.8"

x-env:
  &env
  - LOGLEVEL=${LOGLEVEL}
  - MODE=${MODE}

  # Analyzer
  - ANALYSIS_INTERVAL_IN_SECOND=${ANALYSIS_INTERVAL_IN_SECOND}
  - ANALYSIS_WAITTIME=${ANALYSIS_WAITTIME}
  - TEXT_INFERENCE_PRETRAINED=${TEXT_INFERENCE_PRETRAINED}

  # Binance
  - BINANCE_API_KEY=${BINANCE_API_KEY}
  - BINANCE_API_SECRET=${BINANCE_API_SECRET}

  # Slack
  - SLACK_TOKEN=${SLACK_TOKEN}
  - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
  - SLACK_USER_ID=${SLACK_USER_ID}

  # Reddit
  - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
  - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
  - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}

  # Twitter
  - TWEEPY_CONSUMER_KEY=${TWEEPY_CONSUMER_KEY}
  - TWEEPY_CONSUMER_SECRET=${TWEEPY_CONSUMER_SECRET}
  - TWEEPY_ACCESS_TOKEN=${TWEEPY_ACCESS_TOKEN}
  - TWEEPY_ACCESS_TOKEN_SECRET=${TWEEPY_ACCESS_TOKEN_SECRET}

x-data-dir: &data-dir ${DATA_DIR}:/data
x-common-utils-dir: &common-utils-dir ./common_utils:/home/${USERNAME}/app/common_utils:ro
x-configs-dir: &configs-dir ./configs/:/home/${USERNAME}/app/configs:ro
x-restart-policy: &restart on-failure:2

x-build-args:
  &build-args
  context: ./
  args:
    USERNAME: ${USERNAME}
    USER_ID: ${USER_ID}
    GROUP_ID: ${GROUP_ID}
    TZ: ${TZ}

services:
  slackbot:
    image: catbot:${VERSION}
    hostname: slackbot
    container_name: slackbot
    build: *build-args
    volumes:
      - ./slackbot:/home/${USERNAME}/app
      - *configs-dir
      - *common-utils-dir
      - *data-dir
    environment: *env
    restart: *restart
    command: python3 main.py

  binance_stats_analyzer:
    image: catbot:${VERSION}
    hostname: binance_stats_analyzer
    container_name: binance_stats_analyzer
    build: *build-args
    volumes:
      - ./binance_stats_analyzer:/home/${USERNAME}/app
      - *configs-dir
      - *common-utils-dir
      - *data-dir
    environment: *env
    restart: *restart
    command: python3 main.py

  text_analyzer:
    image: catbot:${VERSION}
    hostname: text_analyzer
    container_name: text_analyzer
    build: *build-args
    volumes:
      - ./text_analyzer:/home/${USERNAME}/app
      - *configs-dir
      - *common-utils-dir
      - *data-dir
    environment: *env
    restart: *restart
    command: python3 main.py

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    volumes:
      - ./mqtt-broker/:/mosquitto/
    ports:
      - 1883:1883
    restart: *restart
