version: "3.8"

services:
  slackbot:
    image: slackbot:${VERSION}
    hostname: slackbot
    container_name: slackbot
    build:
      context: ./
      dockerfile: ./slackbot/Dockerfile
    volumes:
      - ${DATA_DIR}:/data
    env_file:
      - .env
    restart: on-failure:2

  binance_stats_analyzer:
    image: binance_stats_analyzer:${VERSION}
    hostname: binance_stats_analyzer
    container_name: binance_stats_analyzer
    build:
      context: ./
      dockerfile: ./binance_stats_analyzer/Dockerfile
    volumes:
      - ${DATA_DIR}:/data
    env_file:
      - .env
    restart: on-failure:2

  text_analyzer:
    image: text_analyzer:${VERSION}
    hostname: text_analyzer
    container_name: text_analyzer
    build:
      context: ./
      dockerfile: ./text_analyzer/Dockerfile
    volumes:
      - ${DATA_DIR}:/data
    env_file:
      - .env
    restart: on-failure:2

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mqtt-broker
    volumes:
      - ./mqtt-broker/:/mosquitto/
    env_file:
      - .env
    ports:
      - 1883:1883
    restart: on-failure:2
