version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mqtt-broker
    env_file:
      - .env
    volumes:
      - ./mqtt-broker/:/mosquitto/
    ports:
      - 1883:1883

  slack:
    image: slackbot
    hostname: slackbot
    container_name: slackbot
    env_file:
      - .env
    volumes:
      - ./slackbot/:/app/
      - ./common_utils/:/app/common_utils/
