BTCUSDT: ["BTC", "Bitcoin"]
ETHUSDT: ["ETH", "Ethereum"]
BNBUSDT: ["BNB", "Binance", "Binance Coin"]
MATICUSDT: ["MATIC", "Polygon"]
SOLUSDT: ["SOL", "Solana"]
LTCUSDT: ["LTC", "Litecoin"]
SHIBUSDT: ["SHIB", "SHIBA INU", "SHIBA"]
XRPUSDT: ["XRP", "Ripple"]
FILUSDT: ["FIL", "Filecoin"]
APTUSDT: ["APT", "Aptos"]
ADAUSDT: ["ADA", "Cardao"]
